### ISSUE TITLE
"Access denied" trying to open .txt files

### ISSUE THREAD

**Issue by resoli** [nextcloud/files_texteditor#40]
### Steps to reproduce
1. Click on a .txt file

### Expected behaviour
The editor opens showing file content.

### Actual behaviour
An "Access denied" message is shown.

- Editor opens a newly created file.
- Changing extension (e.g. from .txt to .xml) makes the editor able to open file.

### Server configuration

**Operating system**:
Debian jessie
**Web server:**
Apache 2.4
**Database:**
mysql
**PHP version:**
5.6.29
**Nextcloud version:** (see Nextcloud admin page)
11.0.3
**Where did you install Nextcloud from:**

**List of activated apps:**

Enabled:
  - activity: 2.5.2
  - audioplayer: 2.0.1
  - bookmarks: 0.10.0
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notes: 2.2.0
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - richdocuments: 1.12.31
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreed: 2.0.1
  - spreedme: 0.3.9
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0

**Comment by resoli** [comment]
Enabled apps list is wrong, the followong is correct:
- activity: 2.5.2
  - audioplayer: 2.0.1
  - bookmarks: 0.10.0
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notes: 2.2.0
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - richdocuments: 1.12.31
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreed: 2.0.1
  - spreedme: 0.3.9
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0

**Comment by phasenohr** [comment]
I am facing exactly the same problem on 11.0.3. I can create a .txt file and put some content inside but once I close it, I cannot open it again for editing (although I can download it). Renaming the file with a different extension like .xml enables editing again. 
It might be worth noting that there is not any problem with libreoffice (repeated editing of the same .odt file works just fine).

Has it been fixed in 11.0.4?

**Comment by jm009** [comment]
At @resolie and @phasenohr: Does the problem still persist?
Can it be, that the webserver or fastcgi runs under another user than the file permissions on disk?

**Comment by resoli** [comment]
No problem under NC 13.0.1

**Comment by phasenohr** [comment]
@jm009, There is no problem any more in NC13.0.0
Thanks.
________________________________
